### PR TITLE
Aurelien/component placement

### PR DESCRIPTION
**Pull request by AurelienLesage**

### CODE REVIEW

**Comment by AurelienLesage** [comment]
Had a conflit on the .pcb file but i managed to take the version i worked on, as i wrote in the commit desricption : Not the final version of the PCB, missing components for the antenna (i need to recheck the components i choose) and also non-component things like the astroplant logo, the version and placement of the component designators. 
Then we will be able to generate the output file.

**Comment by AurelienLesage** [comment]
I don't know if this version includes the
Fix of the absolute paths, but my last commit didn't include any modification on "fp-lib-table" so maybe it's ok, if you can check.

**Comment by fgolinski** [comment]
Oops, you accidentally committed conflicting sections including "======" stuff. I think I fixed it, now it looks ok on my machine but please double check.

**Comment by fgolinski** [comment]
I am still getting an error related to antenna, it would make sense to finish it before merging.

**Comment by AurelienLesage** [comment]
> I am still getting an error related to antenna, it would make sense to finish it before merging.
Solved in the new push, you can check for the project, like generate Gerber to see if it work for you,
I will look this afternoon at board manufacturer now that i have the gerber generated

**Comment by fgolinski** [comment]
Looks good on my machine, except the paths (so I fixed them again).
Should not xml files be ignored?

**Comment by AurelienLesage** [comment]
> Should not xml files be ignored?
I add it to the gitignore

**Pull request merged**
